const EXPO_PUBLIC_LOCAL_DB_NAME = process.env
  .EXPO_PUBLIC_LOCAL_DB_NAME as string;
const EXPO_PUBLIC_SUPABASE_URL = process.env.EXPO_PUBLIC_SUPABASE_URL as string;
const EXPO_PUBLIC_SUPABASE_KEY = process.env.EXPO_PUBLIC_SUPABASE_KEY as string;

export const env = {
  EXPO_PUBLIC_LOCAL_DB_NAME,
  EXPO_PUBLIC_SUPABASE_URL,
  EXPO_PUBLIC_SUPABASE_KEY,
};
